//
//  REViewController.m
//  REAutoComplete
//
//  Created by Rinat Enikeev on 07/25/2016.
//  Copyright (c) 2016 Rinat Enikeev. All rights reserved.
//

#import "REViewController.h"
#import <REAutoComplete/REAutoComplete.h>

@interface NSString (REAutoCompleteItem) <REAutoCompleteItem>
@end

@implementation NSString (REAutoCompleteItem)
- (NSString*)autoCompleteText {
    return self;
}
@end

@interface REViewController () <REAutoCompleteDelegate>
@property (weak, nonatomic) IBOutlet UITextField *textField;
@end

@implementation REViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    id<REAutoCompleteAlgorithm> algorithm = [[REAutoCompleteAlgorithmContains alloc] initWithSuggestions:self.countryArray];
    self.textField.autoComplete.algorithm = algorithm;
    self.textField.autoComplete.delegate = self;
}

#pragma mark <REAutoCompleteDelegate>
- (void)autoComplete:(REAutoComplete*)autoComplete didSelectObject:(id<REAutoCompleteItem>)object {
    self.textField.text = [object autoCompleteText];
}

- (NSArray<id<REAutoCompleteItem>>*)countryArray {
    return @[
             @"Abkhazia",
             @"Abkhazia",
             @"Afghanistan",
             @"Albania",
             @"Algeria",
             @"American Samoa",
             @"Andorra",
             @"Angola",
             @"Anguilla",
             @"Antigua and Barbuda",
             @"Argentina",
             @"Armenia",
             @"Aruba",
             @"Ascension",
             @"Australia",
             @"Australian External Territories",
             @"Austria",
             @"Azerbaijan",
             @"Bahamas",
             @"Bahrain",
             @"Bangladesh",
             @"Barbados",
             @"Barbuda",
             @"Belarus",
             @"Belgium",
             @"Belize",
             @"Benin",
             @"Bermuda",
             @"Bhutan",
             @"Bolivia",
             @"Bosnia and Herzegovina",
             @"Botswana",
             @"Brazil",
             @"British Indian Ocean Territory",
             @"British Virgin Islands",
             @"Brunei",
             @"Bulgaria",
             @"Burkina Faso",
             @"Burundi",
             @"Cambodia",
             @"Cameroon",
             @"Canada",
             @"Cape Verde",
             @"Cayman Islands",
             @"Central African Republic",
             @"Chad",
             @"Chile",
             @"China",
             @"Christmas Island",
             @"Cocos-Keeling Islands",
             @"Colombia",
             @"Comoros",
             @"Congo",
             @"Congo, Dem. Rep. of (Zaire)",
             @"Cook Islands",
             @"Costa Rica",
             @"Ivory Coast",
             @"Croatia",
             @"Cuba",
             @"Curacao",
             @"Cyprus",
             @"Czech Republic",
             @"Denmark",
             @"Diego Garcia",
             @"Djibouti",
             @"Dominica",
             @"Dominican Republic",
             @"Dominican Republic",
             @"Dominican Republic",
             @"East Timor",
             @"Easter Island",
             @"Ecuador",
             @"Egypt",
             @"El Salvador",
             @"Equatorial Guinea",
             @"Eritrea",
             @"Estonia",
             @"Ethiopia",
             @"Falkland Islands",
             @"Faroe Islands",
             @"Fiji",
             @"Finland",
             @"France",
             @"French Antilles",
             @"French Guiana",
             @"French Polynesia",
             @"Gabon",
             @"Gambia",
             @"Georgia",
             @"Germany",
             @"Ghana",
             @"Gibraltar",
             @"Greece",
             @"Greenland",
             @"Grenada",
             @"Guadeloupe",
             @"Guam",
             @"Guatemala",
             @"Guinea",
             @"Guinea-Bissau",
             @"Guyana",
             @"Haiti",
             @"Honduras",
             @"Hong Kong SAR China",
             @"Hungary",
             @"Iceland",
             @"India",
             @"Indonesia",
             @"Iran",
             @"Iraq",
             @"Ireland",
             @"Israel",
             @"Italy",
             @"Jamaica",
             @"Japan",
             @"Jordan",
             @"Kazakhstan",
             @"Kenya",
             @"Kiribati",
             @"North Korea",
             @"South Korea",
             @"Kuwait",
             @"Kyrgyzstan",
             @"Laos",
             @"Latvia",
             @"Lebanon",
             @"Lesotho",
             @"Liberia",
             @"Libya",
             @"Liechtenstein",
             @"Lithuania",
             @"Luxembourg",
             @"Macau SAR China",
             @"Macedonia",
             @"Madagascar",
             @"Malawi",
             @"Malaysia",
             @"Maldives",
             @"Mali",
             @"Malta",
             @"Marshall Islands",
             @"Martinique",
             @"Mauritania",
             @"Mauritius",
             @"Mayotte",
             @"Mexico",
             @"Micronesia",
             @"Midway Island",
             @"Micronesia",
             @"Moldova",
             @"Monaco",
             @"Mongolia",
             @"Montenegro",
             @"Montserrat",
             @"Morocco",
             @"Myanmar",
             @"Namibia",
             @"Nauru",
             @"Nepal",
             @"Netherlands",
             @"Netherlands Antilles",
             @"Nevis",
             @"New Caledonia",
             @"New Zealand",
             @"Nicaragua",
             @"Niger",
             @"Nigeria",
             @"Niue",
             @"Norfolk Island",
             @"Northern Mariana Islands",
             @"Norway",
             @"Oman",
             @"Pakistan",
             @"Palau",
             @"Palestinian Territory",
             @"Panama",
             @"Papua New Guinea",
             @"Paraguay",
             @"Peru",
             @"Philippines",
             @"Poland",
             @"Portugal",
             @"Puerto Rico",
             @"Puerto Rico",
             @"Qatar",
             @"Reunion",
             @"Romania",
             @"Russia",
             @"Rwanda",
             @"Samoa",
             @"San Marino",
             @"Saudi Arabia",
             @"Senegal",
             @"Serbia",
             @"Seychelles",
             @"Sierra Leone",
             @"Singapore",
             @"Slovakia",
             @"Slovenia",
             @"Solomon Islands",
             @"South Africa",
             @"South Georgia and the South Sandwich Islands",
             @"Spain",
             @"Sri Lanka",
             @"Sudan",
             @"Suriname",
             @"Swaziland",
             @"Sweden",
             @"Switzerland",
             @"Syria",
             @"Taiwan",
             @"Tajikistan",
             @"Tanzania",
             @"Thailand",
             @"Timor Leste",
             @"Togo",
             @"Tokelau",
             @"Tonga",
             @"Trinidad and Tobago",
             @"Tunisia",
             @"Turkey",
             @"Turkmenistan",
             @"Turks and Caicos Islands",
             @"Tuvalu",
             @"Uganda",
             @"Ukraine",
             @"United Arab Emirates",
             @"United Kingdom",
             @"United States",
             @"Uruguay",
             @"U.S. Virgin Islands",
             @"Uzbekistan",
             @"Vanuatu",
             @"Venezuela",
             @"Vietnam",
             @"Wake Island",
             @"Wallis and Futuna",
             @"Yemen",
             @"Zambia",
             @"Zanzibar",
             @"Zimbabwe"
             ];
}

@end
